# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

before_all do |lane, options|
  clear_derived_data
  clean_build_artifacts
end

platform :ios do
  desc "Description of what the lane does"
  lane :build do
    get_certificates
    get_provisioning_profile
    gym
    scan
  end

  lane :test do
    get_certificates
    get_provisioning_profile
    gym
    scan
    xcov
  end
end
