update_fastlane

default_platform(:ios)

before_all do |lane, options|
  clear_derived_data
  clean_build_artifacts
end

platform :ios do
  desc "Description of what the lane does"
  lane :build do
    get_certificates
    get_provisioning_profile
    gym
    scan
  end

  lane :test do
    get_certificates
    get_provisioning_profile
    gym
    scan
    xcov
  end
end
