name: iOS Build Workflow

on:
  push:
    branches:
    - main
    - '30-add-fastlane-support'

jobs:
  build-and-test:
    name: Prepare the Environment
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4 
      - name: Setup Fastlane
        run: |
          pwd
          ls -a
          bundle install
        working-directory: ${{ github.workspace }}
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Build the app
        run: |
          pwd
          ls -a
          bundle exec fastlane build
        working-directory: ${{ github.workspace }}
      - name: Test
        run: |
          pwd
          ls -a
          bundle exec fastlane test
        working-directory: ${{ github.path }}
