name: iOS starter workflow

on:
  push:
    branches:
    - main
    - '**fastlane'

jobs:
  build:
    name: Build the application.
    runs-on: macos-14

    steps:
      - name: "Setup"
        run: |
          brew install
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Checkout
        uses: actions/checkout@v4 
      - name: Build the app
        run: |
          bundle exec fastlane build
        
      - name: Test
        run: |
          bundle exec fastlane test
